# Generated by Django 2.2 on 2019-05-16 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20190516_0116'),
        ('activities', '0003_activity_plantraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chrono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=10)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
