# Generated by Django 2.2 on 2019-05-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chrono',
            name='timechrono',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
