# Generated by Django 2.2 on 2019-05-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chrono', '0002_chrono_timechrono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrono',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
    ]
