export const LOGIN = '/auth/login'
export const SIGN_UP = '/signup'
export const SEARCH = '/search'
export const PROFILE = '/profile'
export const TRAININGS = '/trainings'
export const ACTIVITIES = '/activities'
