export const LOGIN = '/auth/login'
export const SIGN_UP = '/signup/'
export const SEARCH = '/search'
export const PROFILE = '/profile'
export const CHRONOMETER = '/chronometer'
export const TRAININGS = '/trainingsPlan/:idPlan/trainings/'
export const ACTIVITIES = '/trainingsPlan/:idPlan/trainings/:idTraining/activities'
