# Generated by Django 2.2 on 2019-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('meters', models.IntegerField()),
                ('exercise', models.TextField(max_length=20)),
                ('style', models.TextField(max_length=20)),
                ('type', models.TextField(max_length=20)),
                ('rhythm', models.TextField(max_length=20)),
            ],
        ),
    ]
