# Generated by Django 2.2 on 2019-05-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0010_auto_20190501_0041'),
        ('activities', '0002_activity_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='plantraining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantrainings.PlanTraining'),
        ),
    ]
