pipeline {
  agent any
  environment {
    CI = 'true'
    HOME = '.'
  }
  stages {
    stage ('Install Dependecies') {
      steps {
        dir ("back/") {
          sh 'pip install -r requirements.txt'
        }
      }
    }
    stage ('Test') {
      steps {
        dir ("back/") {
          sh 'python manage.py test'
        }
      }
    }
    stage ('Deploy') {
      steps {
        dir ("back/") {
          sh 'python manage.py runserver'
        }
      }
    }


  }
}