pipeline {
  agent any
  environment {
    CI = 'true'
    HOME = '.'
  }
  stages {
    stage ('Install Dependecies') {
      steps {
        dir ("back/") {
          sh 'pip3 install -r requirements.txt'
        }
      }
    }
    stage ('Test') {
      steps {
        dir ("back/") {
          sh 'python3 manage.py test'
        }
      }
    }
    stage ('Deploy') {
      steps {
        dir ("back/") {
          sh 'python3 manage.py runserver &'
        }
      }
    }
  }
  post {
      success {
        slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
      }
      failure {
        slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
      }
  }
}