export const ADD_CHRONO = 'ADD_CHRONO'
export const GET_CHRONO_BY_IDUSER = 'GET_CHRONO_BY_IDUSER'
export const GET_CHRONO_BY_IDACTIVITY = 'GET_CHRONO_BY_IDACTIVITY'
export const DELETE_CHRONO = 'DELETE_CHRONO'
