export const USER_LOGIN = 'USER_LOGIN'
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGOUT = 'USER_LOGOUT'
export const AUTHENTICATE = 'AUTHENTICATE'
export const MODIFY_USER = 'MODIFY_USER'