# Generated by Django 2.2 on 2019-05-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chrono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePhase', models.TextField(max_length=10)),
                ('chrono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chrono.Chrono')),
            ],
        ),
    ]
