# Generated by Django 2.2 on 2019-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phases',
            name='meters',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
