pipeline {
  agent {
    docker {
      image 'node:10-alpine'
    }
  }
  environment {
    HOME = '.'
  }
  stages {
    stage ('Build') {

      steps {
        dir ("front/") {
          sh 'npm install'
        }
      }
    }
  }
}