pipeline {
  agent {
    docker {
      image 'node:10-alpine'
    }
  }
  stages {
    stage ('Build') {

      steps {
        dir ("front") {
          sh 'sudo npm install'
        }
      }
    }
  }
}