# Generated by Django 2.2 on 2019-04-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='planTraining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plantrainings.PlanTraining'),
        ),
    ]
