# Generated by Django 2.2 on 2019-04-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_training_plantraining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='planTraining',
            new_name='plantraining',
        ),
    ]
