# Generated by Django 2.2 on 2019-05-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20190426_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='plantraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantrainings.PlanTraining'),
        ),
    ]
