# Generated by Django 2.2 on 2019-05-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20190502_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
    ]
