# Generated by Django 2.2 on 2019-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20190504_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='timetraining',
            field=models.BigIntegerField(),
        ),
    ]
