# Generated by Django 2.2 on 2019-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20190504_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
