# Generated by Django 2.2 on 2019-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20190520_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
