# Generated by Django 2.2 on 2019-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190429_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CN Las Palmas'), (2, 'CN Fainagua C. Telde'), (3, 'CN Salinas Sta.Lucia'), (4, 'CN Metropole')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=32),
        ),
    ]
