# Generated by Django 2.2 on 2019-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('plantrainings', '0003_auto_20190429_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantraining',
            name='user',
        ),
        migrations.AddField(
            model_name='plantraining',
            name='user',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
