# Generated by Django 2.2 on 2019-04-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190429_2345'),
        ('plantrainings', '0004_auto_20190429_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantraining',
            name='user',
        ),
        migrations.AddField(
            model_name='plantraining',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
