# Generated by Django 2.2 on 2019-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190429_2345'),
        ('plantrainings', '0005_auto_20190430_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantraining',
            name='user',
        ),
        migrations.AddField(
            model_name='plantraining',
            name='user',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
