# Generated by Django 2.2 on 2019-05-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0006_auto_20190430_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraining',
            name='user',
            field=models.ManyToManyField(related_name='firsts', to='users.User'),
        ),
    ]
