# Generated by Django 2.2 on 2019-05-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0009_auto_20190501_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantraining',
            old_name='userid',
            new_name='user',
        ),
    ]
