# Generated by Django 2.2 on 2019-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0010_auto_20190501_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraining',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
