# Generated by Django 2.2 on 2019-05-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantrainings', '0012_auto_20190521_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantraining',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
